stages:
  - deploy
Deploy: 
  stage: deploy
  tags:
    - armerge-backend
  before_script:
  - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )' 
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $EC2_IPADDRESS >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - zip -r public.zip public
    - scp -o StrictHostKeyChecking=no public.zip ubuntu@ec2-18-139-83-155.ap-southeast-1.compute.amazonaws.com:~/backend
    - ssh -o StrictHostKeyChecking=no ubuntu@ec2-18-139-83-155.ap-southeast-1.compute.amazonaws.com "cd ~/backend; rm -rf ./public; unzip public.zip; cd ~/backend/public; npm i; npm run build; pm2 start backend"