export enum TEAM_MEMBER_ROLE {
    TEAM_LEAD = 'TEAM_LEAD',
    MEMBER = 'MEMBER',
}

export enum TEAM_MEMBER_TYPE {
    THREE_D = '3D',
    AGENCY = 'AGENCY',
}

export enum TEAM_MEMBER_STATUS {
    INVITED = 'INVITED',
    ACTIVE = 'ACTIVE',
    DISABLED = 'DISABLED',
}

export enum PLATFORMS {
    SHOPIFY = 'SHOPIFY',
    MAGNETO = 'MAGNETO',
    WOOCOMMERCE = 'WOOCOMMERCE',
}
